"""
discovery_summary_engine.py
===========================
Scientific Research Snapshot and Intelligence Synthesis Module.

Compiles a high-level summary of habitable exoplanet discoveries, 
statistical distributions, and top-tier candidates. Exports results 
to the 'exoplanet_data' DB schema and a formal markdown report.
"""

import os
import pandas as pd
from datetime import datetime
from src.config.config import config
from src.utils.logger import setup_logger
from src.utils.db import get_engine

logger = setup_logger("DiscoverySummaryEngine")

def generate_discovery_snapshot():
    """Generates a comprehensive scientific snapshot from current database state."""
    logger.info("Initializing Discovery Intelligence Synthesis...")
    engine = get_engine()
    
    try:
        # 1. Total Habitat Candidates and Average Scores
        counts_df = pd.read_sql("SELECT COUNT(*) as discovered, AVG(combined_discovery_score) as avg_score FROM exoplanet_data.habitable_planet_candidates", engine)
        discovered_count = counts_df.iloc[0]["discovered"]
        avg_score = counts_df.iloc[0]["avg_score"]

        # 2. Distribution of Discovery Methods for Habitable Candidates
        methods_df = pd.read_sql("SELECT discovery_method, COUNT(*) as count FROM exoplanet_data.habitable_planet_candidates GROUP BY discovery_method ORDER BY count DESC", engine)
        
        # 3. Average Stellar Temperatures of Candidate Systems
        temp_df = pd.read_sql("SELECT AVG(stellar_temperature) as avg_st_teff FROM exoplanet_data.habitable_planet_candidates", engine)
        avg_st_teff = temp_df.iloc[0]["avg_st_teff"]

        # 4. Top 5 Prioritized Candidates
        top_5_df = pd.read_sql("SELECT planet_name, combined_discovery_score, discovery_method, host_star FROM exoplanet_data.habitable_planet_candidates ORDER BY combined_discovery_score DESC LIMIT 5", engine)

        # 5. Persistent DB Snapshot
        logger.info("Persisting snapshot to exoplanet_data.discovery_summary_snapshot...")
        summary_data = {
            "timestamp": datetime.now().isoformat(),
            "total_discovered": int(discovered_count),
            "average_score": float(avg_score) if avg_score else 0.0,
            "avg_stellar_temp": float(avg_st_teff) if avg_st_teff else 0.0,
            "top_candidate": top_5_df.iloc[0]["planet_name"] if not top_5_df.empty else "None"
        }
        pd.DataFrame([summary_data]).to_sql("discovery_summary_snapshot", schema="exoplanet_data", con=engine, if_exists="replace", index=False)

        # 6. Generate Markdown Report
        report_path = os.path.join("reports", "discovery_snapshot.md")
        logger.info(f"Generating formal markdown report at {report_path}...")
        
        report_content = f"""# ExoIntel Discovery Intelligence Snapshot
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Platform Version**: v1.5.0-intelligence

## 1. Discovery Overview
| Metric | Value |
|--------|-------|
| Total Habitable Candidates | {discovered_count:,} |
| Average Discovery Score | {avg_score:.4f} |
| Mean Stellar Effective Temp | {avg_st_teff:.2f} K |

## 2. Top-Tier Research Candidates
| Rank | Planet Name | Discovery Score | Discovery Method | Host Star |
|------|-------------|-----------------|------------------|-----------|
"""
        for i, row in top_5_df.iterrows():
            report_content += f"| {i+1} | **{row['planet_name']}** | {row['combined_discovery_score']:.4f} | {row['discovery_method']} | {row['host_star']} |\n"

        report_content += "\n## 3. Discovery Method Distribution\n"
        report_content += "| Method | Yield (Candidates) |\n|--------|-------------------|\n"
        for _, row in methods_df.iterrows():
            report_content += f"| {row['discovery_method']} | {row['count']} |\n"

        report_content += "\n--- \n*This report is automatically generated by the ExoIntel Discovery Intelligence Engine.*"

        with open(report_content_file := report_path, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        logger.info("Discovery summary report successfully exported.")

    except Exception as e:
        logger.error(f"Intelligence synthesis failed: {e}")
        raise

if __name__ == "__main__":
    generate_discovery_snapshot()
